<?php
$pageTitle = 'Smart Campus Nova Hub - Report Details';
$pageIcon = 'fas fa-file-alt';
$pageHeading = 'Report Details';
$activePage = 'reports';

ob_start();
?>

<!-- Compact Page Header -->
<div class="page-header-compact">
    <div class="page-icon-compact">
        <i class="fas fa-file-alt"></i>
    </div>
    <div class="page-title-compact">
        <h2>Report Details</h2>
        <p style="font-size: 14px; color: #666; margin: 4px 0 0 0;">View and manage comprehensive school reports</p>
    </div>
    <div style="display: flex; gap: 12px; margin-left: auto;">
        <button class="simple-btn secondary" onclick="window.location.href='/admin/report-centre'">
            <i class="fas fa-arrow-left"></i> Back to Reports
        </button>
        <button class="simple-btn secondary" onclick="printReport()">
            <i class="fas fa-print"></i> Print
        </button>
        <button class="simple-btn" onclick="downloadReport()">
            <i class="fas fa-download"></i> Download
        </button>
    </div>
</div>

<!-- Report Information -->
<div class="simple-section">
    <div class="simple-header">
        <h3><i class="fas fa-info-circle"></i> Report Information</h3>
    </div>
    
    <div class="report-info-grid">
        <div class="info-item">
            <label>Report Name</label>
            <span id="reportName">Student Performance Analysis Q1 2025</span>
        </div>
        <div class="info-item">
            <label>Report Type</label>
            <span><span class="badge-type academic">Academic Report</span></span>
        </div>
        <div class="info-item">
            <label>Generated By</label>
            <span id="generatedBy">Admin User</span>
        </div>
        <div class="info-item">
            <label>Date Generated</label>
            <span id="dateGenerated">2025-01-15 14:30</span>
            </div>
        <div class="info-item">
            <label>Period Covered</label>
            <span id="periodCovered">January 2025</span>
            </div>
        <div class="info-item">
            <label>Status</label>
            <span><span class="status-badge completed">Completed</span></span>
        </div>
    </div>
</div>

<!-- Report Summary -->
<div class="simple-section">
    <div class="simple-header">
        <h3><i class="fas fa-chart-line"></i> Executive Summary</h3>
    </div>
    
    <div class="summary-cards">
        <div class="summary-card">
            <div class="summary-icon">
                <i class="fas fa-users"></i>
            </div>
            <div class="summary-content">
                <h4>Total Students</h4>
                <div class="summary-number">1,247</div>
                <div class="summary-change positive">+12 this month</div>
            </div>
        </div>
        <div class="summary-card">
            <div class="summary-icon">
                <i class="fas fa-graduation-cap"></i>
            </div>
            <div class="summary-content">
                <h4>Average Performance</h4>
                <div class="summary-number">87.5%</div>
                <div class="summary-change positive">+3.2% vs last term</div>
            </div>
        </div>
        <div class="summary-card">
            <div class="summary-icon">
                <i class="fas fa-chart-bar"></i>
            </div>
            <div class="summary-content">
                <h4>Top Performing Grade</h4>
                <div class="summary-number">Grade 10</div>
                <div class="summary-change">92.3% average</div>
            </div>
        </div>
        <div class="summary-card">
            <div class="summary-icon">
                <i class="fas fa-book"></i>
            </div>
            <div class="summary-content">
                <h4>Best Subject</h4>
                <div class="summary-number">Mathematics</div>
                <div class="summary-change">89.7% average</div>
            </div>
            </div>
        </div>
    </div>

<!-- Report Content Sections -->
<div class="simple-section">
    <div class="simple-header">
        <h3><i class="fas fa-chart-pie"></i> Performance Analysis</h3>
        </div>
    
    <div class="report-content">
        <div class="content-section">
            <h4>Grade-wise Performance</h4>
            <div class="performance-table">
                <table class="basic-table">
                    <thead>
                        <tr>
                            <th>Grade</th>
                            <th>Total Students</th>
                            <th>Average Score</th>
                            <th>Pass Rate</th>
                            <th>Top Performer</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Grade 7</strong></td>
                            <td>156</td>
                            <td>84.2%</td>
                            <td><span class="status-badge completed">96.8%</span></td>
                            <td>Sarah Johnson (98.5%)</td>
                        </tr>
                        <tr>
                            <td><strong>Grade 8</strong></td>
                            <td>142</td>
                            <td>86.7%</td>
                            <td><span class="status-badge completed">98.6%</span></td>
                            <td>Michael Chen (97.2%)</td>
                        </tr>
                        <tr>
                            <td><strong>Grade 9</strong></td>
                            <td>138</td>
                            <td>88.1%</td>
                            <td><span class="status-badge completed">99.3%</span></td>
                            <td>Emma Davis (99.1%)</td>
                        </tr>
                        <tr>
                            <td><strong>Grade 10</strong></td>
                            <td>134</td>
                            <td>92.3%</td>
                            <td><span class="status-badge completed">100%</span></td>
                            <td>Alex Wilson (99.8%)</td>
                        </tr>
                        <tr>
                            <td><strong>Grade 11</strong></td>
                            <td>129</td>
                            <td>89.4%</td>
                            <td><span class="status-badge completed">98.4%</span></td>
                            <td>Lisa Brown (98.9%)</td>
                        </tr>
                        <tr>
                            <td><strong>Grade 12</strong></td>
                            <td>125</td>
                            <td>91.7%</td>
                            <td><span class="status-badge completed">99.2%</span></td>
                            <td>David Lee (99.5%)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="content-section">
            <h4>Subject-wise Analysis</h4>
            <div class="subject-performance">
                <div class="subject-item">
                    <div class="subject-info">
                        <span class="subject-name">Mathematics</span>
                        <span class="subject-score">89.7%</span>
                    </div>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: 89.7%"></div>
                    </div>
                </div>
                <div class="subject-item">
                    <div class="subject-info">
                        <span class="subject-name">Science</span>
                        <span class="subject-score">87.3%</span>
                    </div>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: 87.3%"></div>
                    </div>
                </div>
                <div class="subject-item">
                    <div class="subject-info">
                        <span class="subject-name">English</span>
                        <span class="subject-score">85.9%</span>
                    </div>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: 85.9%"></div>
                    </div>
                </div>
                <div class="subject-item">
                    <div class="subject-info">
                        <span class="subject-name">Social Studies</span>
                        <span class="subject-score">83.2%</span>
                    </div>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: 83.2%"></div>
                    </div>
                </div>
                <div class="subject-item">
                    <div class="subject-info">
                        <span class="subject-name">Computer Science</span>
                        <span class="subject-score">91.4%</span>
                    </div>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: 91.4%"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="content-section">
            <h4>Key Insights</h4>
            <div class="insights-list">
                <div class="insight-item positive">
                    <i class="fas fa-check-circle"></i>
                    <span>Grade 10 shows exceptional performance with 100% pass rate</span>
                </div>
                <div class="insight-item positive">
                    <i class="fas fa-arrow-up"></i>
                    <span>Overall performance improved by 3.2% compared to last term</span>
                </div>
                <div class="insight-item info">
                    <i class="fas fa-info-circle"></i>
                    <span>Computer Science is the top-performing subject at 91.4%</span>
                </div>
                <div class="insight-item warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    <span>Social Studies shows room for improvement at 83.2%</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Report Actions -->
<div class="simple-section">
    <div class="simple-header">
        <h3><i class="fas fa-cogs"></i> Report Actions</h3>
    </div>
    
    <div class="action-buttons">
        <button class="simple-btn" onclick="shareReport()">
            <i class="fas fa-share"></i> Share Report
        </button>
        <button class="simple-btn secondary" onclick="scheduleReport()">
            <i class="fas fa-clock"></i> Schedule Report
        </button>
        <button class="simple-btn secondary" onclick="exportReport()">
            <i class="fas fa-file-export"></i> Export Data
        </button>
        <button class="simple-btn secondary" onclick="editReport()">
            <i class="fas fa-edit"></i> Edit Report
        </button>
        <button class="simple-btn danger" onclick="deleteReport()">
            <i class="fas fa-trash"></i> Delete Report
        </button>
    </div>
</div>

<!-- Include Shared Styles -->
<link rel="stylesheet" href="/css/shared/fee-management.css">

<style>
/* Report Details Specific Styles */
.report-info-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 20px;
    margin-top: 20px;
    padding: 0 4px;
}

.info-item {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 16px 20px;
    background: #f8fafc;
    border-radius: 8px;
    border: 1px solid #e2e8f0;
}

.info-item label {
    font-size: 11px;
    font-weight: 600;
    color: #64748b;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 2px;
}

.info-item span {
    font-size: 15px;
    color: #1e293b;
    font-weight: 500;
    line-height: 1.4;
}

.summary-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
    gap: 20px;
    margin-top: 20px;
    padding: 0 4px;
}

.summary-card {
    background: #fff;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 24px;
    display: flex;
    align-items: center;
    gap: 18px;
    transition: all 0.3s ease;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.summary-card:hover {
    border-color: #3b82f6;
    box-shadow: 0 8px 25px rgba(59, 130, 246, 0.15);
    transform: translateY(-2px);
}

.summary-icon {
    width: 52px;
    height: 52px;
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 22px;
    color: #3b82f6;
    background: #eff6ff;
    flex-shrink: 0;
}

.summary-content {
    flex: 1;
    min-width: 0;
}

.summary-content h4 {
    margin: 0 0 6px 0;
    font-size: 14px;
    font-weight: 600;
    color: #64748b;
    line-height: 1.3;
}

.summary-number {
    font-size: 26px;
    font-weight: 700;
    color: #1e293b;
    margin-bottom: 6px;
    line-height: 1.2;
}

.summary-change {
    font-size: 13px;
    font-weight: 500;
    line-height: 1.3;
}

.summary-change.positive {
    color: #059669;
}

.report-content {
    margin-top: 24px;
    padding: 0 4px;
}

.content-section {
    margin-bottom: 40px;
    padding: 24px;
    background: #fff;
    border-radius: 12px;
    border: 1px solid #e2e8f0;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.content-section h4 {
    margin: 0 0 20px 0;
    font-size: 18px;
    font-weight: 600;
    color: #1e293b;
    padding-bottom: 12px;
    border-bottom: 2px solid #f1f5f9;
}

.performance-table {
    overflow-x: auto;
    margin-top: 8px;
}

.performance-table table {
    margin: 0;
}

.performance-table th,
.performance-table td {
    padding: 16px 20px;
    border-bottom: 1px solid #f1f5f9;
}

.performance-table th {
    background: #f8fafc;
    font-weight: 600;
    color: #374151;
    font-size: 14px;
}

.performance-table td {
    font-size: 14px;
    color: #4b5563;
}

.subject-performance {
    display: flex;
    flex-direction: column;
    gap: 20px;
    margin-top: 8px;
}

.subject-item {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 16px 20px;
    background: #f8fafc;
    border-radius: 8px;
    border: 1px solid #e2e8f0;
}

.subject-info {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 4px;
}

.subject-name {
    font-weight: 600;
    color: #374151;
    font-size: 15px;
}

.subject-score {
    font-weight: 700;
    color: #1e293b;
    font-size: 16px;
}

.progress-bar {
    width: 100%;
    height: 10px;
    background: #e2e8f0;
    border-radius: 6px;
    overflow: hidden;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}

.progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #3b82f6, #1d4ed8);
    border-radius: 6px;
    transition: width 0.4s ease;
    box-shadow: 0 1px 3px rgba(59, 130, 246, 0.3);
}

.insights-list {
    display: flex;
    flex-direction: column;
    gap: 16px;
    margin-top: 8px;
}

.insight-item {
    display: flex;
    align-items: flex-start;
    gap: 14px;
    padding: 16px 20px;
    border-radius: 8px;
    font-size: 14px;
    line-height: 1.5;
}

.insight-item.positive {
    background: #f0fdf4;
    color: #166534;
    border: 1px solid #bbf7d0;
}

.insight-item.info {
    background: #eff6ff;
    color: #1e40af;
    border: 1px solid #bfdbfe;
}

.insight-item.warning {
    background: #fffbeb;
    color: #92400e;
    border: 1px solid #fed7aa;
}

.insight-item i {
    font-size: 18px;
    margin-top: 2px;
    flex-shrink: 0;
}

.action-buttons {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
    margin-top: 24px;
    padding: 24px;
    background: #f8fafc;
    border-radius: 12px;
    border: 1px solid #e2e8f0;
}

.simple-btn.danger {
    background: #fee2e2;
    color: #dc2626;
    border: 1px solid #fecaca;
}

.simple-btn.danger:hover {
    background: #fecaca;
    color: #b91c1c;
}

/* Badge Types */
.badge-type.academic {
    background: #e0f2f1;
    color: #00695c;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
}

.badge-type.financial {
    background: #e3f2fd;
    color: #1976d2;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
}

.badge-type.attendance {
    background: #fff3e0;
    color: #ef6c00;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
}

.badge-type.administrative {
    background: #f3e5f5;
    color: #7b1fa2;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
}

.status-badge.completed {
    background: #d1fae5;
    color: #059669;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
}

/* Responsive Design */
@media screen and (max-width: 768px) {
    .report-info-grid {
        grid-template-columns: 1fr;
        gap: 16px;
        margin-top: 16px;
    }
    
    .info-item {
        padding: 14px 16px;
    }
    
    .summary-cards {
        grid-template-columns: 1fr;
        gap: 16px;
        margin-top: 16px;
    }
    
    .summary-card {
        padding: 20px;
        gap: 16px;
    }
    
    .summary-icon {
        width: 48px;
        height: 48px;
        font-size: 20px;
    }
    
    .content-section {
        padding: 20px;
        margin-bottom: 32px;
    }
    
    .subject-item {
        padding: 14px 16px;
    }
    
    .insight-item {
        padding: 14px 16px;
        gap: 12px;
    }
    
    .action-buttons {
        flex-direction: column;
        gap: 12px;
        padding: 20px;
        margin-top: 20px;
    }
    
    .action-buttons .simple-btn {
        width: 100%;
        justify-content: center;
        padding: 12px 20px;
    }
    
    .performance-table th,
    .performance-table td {
        padding: 12px 16px;
    }
}
</style>

<script>
// Report Details JavaScript
let currentReportData = null;

document.addEventListener('DOMContentLoaded', function() {
    loadReportDetails();
});

// Load report details
function loadReportDetails() {
    // This would typically load from URL parameters or API
    const urlParams = new URLSearchParams(window.location.search);
    const reportId = urlParams.get('id') || 'RPT001';
    
    console.log('Loading report details for:', reportId);
    
    // Load report data based on ID
    loadReportData(reportId);
    updateReportInfo();
}

// Load report data based on ID
function loadReportData(reportId) {
    // Simulate different report types based on ID
    const reportData = {
        'RPT001': {
            name: 'Student Performance Analysis Q1 2025',
            type: 'academic',
            generatedBy: 'Admin User',
            date: '2025-01-15 14:30',
            period: 'January 2025',
            status: 'completed'
        },
        'RPT002': {
            name: 'Fee Collection Report January 2025',
            type: 'financial',
            generatedBy: 'Finance Manager',
            date: '2025-01-14 10:15',
            period: 'January 2025',
            status: 'completed'
        },
        'RPT003': {
            name: 'Attendance Summary December 2024',
            type: 'attendance',
            generatedBy: 'Admin User',
            date: '2024-12-31 16:45',
            period: 'December 2024',
            status: 'completed'
        }
    };
    
    const data = reportData[reportId] || reportData['RPT001'];
    currentReportData = data;
}

// Update report information
function updateReportInfo() {
    if (currentReportData) {
        document.getElementById('reportName').textContent = currentReportData.name;
        document.getElementById('generatedBy').textContent = currentReportData.generatedBy;
        document.getElementById('dateGenerated').textContent = currentReportData.date;
        document.getElementById('periodCovered').textContent = currentReportData.period;
        
        // Update report type badge
        const typeBadge = document.querySelector('.badge-type');
        if (typeBadge) {
            typeBadge.textContent = getReportTypeLabel(currentReportData.type);
            typeBadge.className = `badge-type ${currentReportData.type}`;
        }
    }
}

// Get report type label
function getReportTypeLabel(type) {
    const labels = {
        'academic': 'Academic Report',
        'financial': 'Financial Report',
        'attendance': 'Attendance Report',
        'administrative': 'Administrative Report'
    };
    return labels[type] || 'Report';
}

// Print report
function printReport() {
    window.print();
}

// Download report
function downloadReport() {
    showToast('Downloading report...', 'info');
    // Simulate download
    setTimeout(() => {
        showToast('Report downloaded successfully', 'success');
    }, 1000);
}

// Share report
function shareReport() {
    showToast('Opening share options...', 'info');
}

// Schedule report
function scheduleReport() {
    showToast('Opening schedule options...', 'info');
}

// Export report
function exportReport() {
    showToast('Exporting report data...', 'info');
}

// Edit report
function editReport() {
    showToast('Opening report editor...', 'info');
}

// Delete report
function deleteReport() {
    if (confirm('Are you sure you want to delete this report? This action cannot be undone.')) {
        showToast('Report deleted successfully', 'success');
        setTimeout(() => {
            window.location.href = '/admin/report-centre';
        }, 1000);
    }
}
</script>

<?php
$content = ob_get_clean();
include __DIR__ . '/../components/admin-layout.php';
?>