<?php
$pageTitle = 'Smart Campus Nova Hub - Event Calendar';
$pageIcon = 'fas fa-calendar-alt';
$pageHeading = 'Event Calendar';
$activePage = 'event-calendar';

ob_start();
?>

<!-- Compact Page Header -->
<div class="page-header-compact">
    <div class="page-icon-compact">
        <i class="<?php echo $pageIcon; ?>"></i>
    </div>
    <div class="page-title-compact">
        <h2><?php echo $pageHeading; ?></h2>
    </div>
</div>

<!-- Event Category Filter (Top Level) -->
<div class="category-filter-section">
    <h3 class="category-filter-title">Event Categories</h3>
    <div class="category-tags">
        <button class="category-tag active" data-category="academic">
            <span class="tag-dot" style="background: #4285f4;"></span>
            Academic
            <i class="fas fa-check tag-check"></i>
        </button>
        <button class="category-tag active" data-category="sports">
            <span class="tag-dot" style="background: #34a853;"></span>
            Sports
            <i class="fas fa-check tag-check"></i>
        </button>
        <button class="category-tag active" data-category="cultural">
            <span class="tag-dot" style="background: #fbbc04;"></span>
            Cultural
            <i class="fas fa-check tag-check"></i>
        </button>
        <button class="category-tag active" data-category="meeting">
            <span class="tag-dot" style="background: #ea4335;"></span>
            Meetings
            <i class="fas fa-check tag-check"></i>
        </button>
        <button class="category-tag active" data-category="holiday">
            <span class="tag-dot" style="background: #9e9e9e;"></span>
            Holidays
            <i class="fas fa-check tag-check"></i>
        </button>
        <button class="category-tag active" data-category="myanmar">
            <span class="tag-dot" style="background: #ff6b35;"></span>
            Myanmar Calendar
            <i class="fas fa-check tag-check"></i>
        </button>
    </div>
</div>

<!-- Main Calendar Layout -->
<div class="calendar-layout">
    <!-- Sidebar with Mini Calendar & Filters -->
    <div class="calendar-sidebar">
        <!-- Mini Calendar -->
        <div class="mini-calendar-section">
            <div class="mini-calendar-header">
                <button class="mini-nav-btn" id="miniPrev">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <span class="mini-month-label" id="miniMonthLabel">October 2025</span>
                <button class="mini-nav-btn" id="miniNext">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
            <div class="mini-calendar-grid" id="miniCalendar">
                <!-- Mini calendar will be generated by JS -->
            </div>
        </div>

    </div>

    <!-- Main Calendar Area -->
    <div class="calendar-main">
        <div class="simple-section">
            <div class="calendar-header">
                <div class="calendar-nav">
                    <button class="mini-nav-btn" id="prevPeriod">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <h3 id="currentPeriod">October 2025</h3>
                    <button class="mini-nav-btn" id="nextPeriod">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>

                <div class="calendar-view-options">
                    <div class="view-toggle-group">
                        <button class="view-toggle-btn" data-view="day">Day</button>
                        <button class="view-toggle-btn" data-view="week">Week</button>
                        <button class="view-toggle-btn active" data-view="month">Month</button>
                    </div>
                    <button class="simple-btn-icon" title="Search Events">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>

            <!-- Month View -->
            <div class="calendar-view-container" id="monthView">
                <div class="calendar-weekdays">
                    <div class="calendar-weekday">Sun</div>
                    <div class="calendar-weekday">Mon</div>
                    <div class="calendar-weekday">Tue</div>
                    <div class="calendar-weekday">Wed</div>
                    <div class="calendar-weekday">Thu</div>
                    <div class="calendar-weekday">Fri</div>
                    <div class="calendar-weekday">Sat</div>
                </div>
                <div class="calendar-grid" id="monthGrid">
                    <!-- Month grid will be generated by JS -->
                </div>
            </div>

            <!-- Week View -->
            <div class="calendar-view-container" id="weekView" style="display:none;">
                <div class="week-view-grid">
                    <div class="week-time-column">
                        <div class="week-time-header"></div>
                        <div class="week-time-slots" id="weekTimeSlots">
                            <!-- Time slots will be generated by JS -->
                        </div>
                    </div>
                    <div class="week-days-container" id="weekDaysContainer">
                        <!-- Week days will be generated by JS -->
                    </div>
                </div>
            </div>

            <!-- Day View -->
            <div class="calendar-view-container" id="dayView" style="display:none;">
                <div class="day-view-grid">
                    <div class="day-time-column">
                        <div class="day-time-header"></div>
                        <div class="day-time-slots" id="dayTimeSlots">
                            <!-- Time slots will be generated by JS -->
                        </div>
                    </div>
                    <div class="day-events-container" id="dayEventsContainer">
                        <!-- Day events will be generated by JS -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Event Details Modal (hidden by default) -->
<div id="eventModal" class="modal" style="display:none;">
    <div class="modal-content" style="max-width:500px;">
        <div class="modal-header">
            <h3 id="eventModalTitle">Event Details</h3>
            <button class="modal-close" onclick="closeEventModal()">&times;</button>
        </div>
        <div class="modal-body">
            <div class="event-detail-row">
                <i class="fas fa-clock"></i>
                <span id="eventModalTime"></span>
            </div>
            <div class="event-detail-row">
                <i class="fas fa-map-marker-alt"></i>
                <span id="eventModalLocation"></span>
            </div>
            <div class="event-detail-row">
                <i class="fas fa-align-left"></i>
                <span id="eventModalDescription"></span>
            </div>
            <div class="event-detail-row" style="border-bottom:none; padding-top: 4px;">
                <button class="simple-btn" onclick="viewEventDetailFromModal()">
                    <i class="fas fa-external-link-alt"></i> View Event Detail
                </button>
            </div>
        </div>
    </div>
</div>

<style>
/* Category Filter Section (Top Level) */
.category-filter-section {
    margin: 16px 0;
    padding: 16px 20px;
    background: #fff;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.category-filter-title {
    font-size: 1rem;
    font-weight: 600;
    color: #333;
    margin: 0 0 12px 0;
}

.category-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
}

.category-tag {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 8px 16px;
    background: #f5f5f5;
    border: 2px solid #e0e0e0;
    border-radius: 24px;
    font-size: 0.9rem;
    font-weight: 500;
    color: #666;
    cursor: pointer;
    transition: all 0.2s ease;
    position: relative;
}

.category-tag:hover {
    background: #ebebeb;
    border-color: #d0d0d0;
}

.category-tag.active {
    background: #fff;
    border-color: currentColor;
    color: #333;
}

.tag-dot {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    flex-shrink: 0;
}

.tag-check {
    font-size: 0.75rem;
    opacity: 0;
    transition: opacity 0.2s;
}

.category-tag.active .tag-check {
    opacity: 1;
    color: #34a853;
}


/* Main Calendar Layout */
.calendar-layout {
    display: flex;
    gap: 20px;
    margin-top: 0;
}

.calendar-sidebar {
    width: 280px;
    flex-shrink: 0;
}

.calendar-main {
    flex: 1;
    min-width: 0;
}

/* Mini Calendar */
.mini-calendar-section {
    background: #fff;
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 16px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.mini-calendar-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 12px;
}

.mini-month-label {
    font-size: 0.9rem;
    font-weight: 600;
    color: #333;
}

.mini-nav-btn {
    background: none;
    border: none;
    cursor: pointer;
    padding: 4px 8px;
    color: #666;
    border-radius: 4px;
    transition: background 0.2s;
}

.mini-nav-btn:hover {
    background: #f0f0f0;
}

.mini-calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 2px;
}

.mini-day {
    aspect-ratio: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.75rem;
    cursor: pointer;
    border-radius: 4px;
    transition: background 0.2s;
}

.mini-day.weekday-label {
    font-weight: 600;
    color: #666;
    cursor: default;
}

.mini-day.other-month {
    color: #ccc;
}

.mini-day.today {
    background: #1976d2;
    color: #fff;
    font-weight: 600;
}

.mini-day.has-events {
    font-weight: 600;
}

.mini-day:not(.weekday-label):not(.other-month):hover {
    background: #f0f0f0;
}

/* Filter Section */
.filter-section {
    background: #fff;
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 16px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.filter-title {
    font-size: 0.9rem;
    font-weight: 600;
    color: #333;
    margin: 0 0 12px 0;
}

/* Calendar Header */
.calendar-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px 20px;
    background: #fff;
    border-bottom: 1px solid #e0e0e0;
}

.calendar-nav {
    display: flex;
    align-items: center;
    gap: 16px;
    flex: 1;
    max-width: 400px;
}

.calendar-nav h3 {
    margin: 0;
    font-size: 1.3rem;
    font-weight: 600;
    color: #333;
    white-space: nowrap;
    flex: 1;
    text-align: center;
}

.calendar-nav .mini-nav-btn {
    flex-shrink: 0;
}

.calendar-view-options {
    display: flex;
    align-items: center;
    gap: 12px;
}

.view-toggle-group {
    display: flex;
    gap: 4px;
    background: #f0f0f0;
    padding: 4px;
    border-radius: 6px;
}

.view-toggle-btn {
    padding: 6px 16px;
    border: none;
    background: transparent;
    border-radius: 4px;
    cursor: pointer;
    font-size: 0.85rem;
    font-weight: 500;
    color: #666;
    transition: all 0.2s;
}

.view-toggle-btn:hover {
    background: #e0e0e0;
}

.view-toggle-btn.active {
    background: #fff;
    color: #1976d2;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

/* Month View */
.calendar-view-container {
    background: #fff;
    padding: 16px;
}

.calendar-weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: #e0e0e0;
    border: 1px solid #e0e0e0;
    margin-bottom: 1px;
}

.calendar-weekday {
    background: #f8f9fa;
    padding: 12px;
    text-align: center;
    font-weight: 600;
    font-size: 0.85rem;
    color: #666;
}

.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: #e0e0e0;
    border: 1px solid #e0e0e0;
    min-height: 500px;
}

.calendar-day {
    background: #fff;
    min-height: 100px;
    padding: 8px;
    position: relative;
    cursor: pointer;
    transition: background-color 0.2s;
}

.calendar-day:hover {
    background: #f8f9fa;
}

.calendar-day.other-month {
    background: #fafafa;
    color: #999;
}

.calendar-day.today {
    background: #e3f2fd;
}

.calendar-day-number {
    font-size: 0.9rem;
    font-weight: 500;
    color: #333;
    margin-bottom: 4px;
}

.calendar-day.other-month .calendar-day-number {
    color: #999;
}

.calendar-day.today .calendar-day-number {
    background: #1976d2;
    color: #fff;
    width: 24px;
    height: 24px;
    border-radius: 50%;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    font-size: 0.85rem;
}

.calendar-events {
    display: flex;
    flex-direction: column;
    gap: 2px;
    margin-top: 4px;
}

.calendar-event {
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 0.75rem;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    cursor: pointer;
    transition: opacity 0.2s;
    color: #fff;
}

.calendar-event:hover {
    opacity: 0.85;
}

/* Week View */
.week-view-grid {
    display: flex;
    min-height: 600px;
}

.week-time-column {
    width: 80px;
    flex-shrink: 0;
    border-right: 1px solid #e0e0e0;
}

.week-time-header {
    height: 60px;
    border-bottom: 1px solid #e0e0e0;
}

.week-time-slots {
    position: relative;
}

.week-time-slot {
    height: 60px;
    border-bottom: 1px solid #f0f0f0;
    padding: 4px 8px;
    font-size: 0.75rem;
    color: #666;
}

.week-days-container {
    flex: 1;
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background: #e0e0e0;
}

.week-day-column {
    background: #fff;
    position: relative;
}

.week-day-header {
    height: 60px;
    border-bottom: 1px solid #e0e0e0;
    padding: 8px;
    text-align: center;
}

.week-day-name {
    font-size: 0.75rem;
    color: #666;
    font-weight: 600;
}

.week-day-date {
    font-size: 1.2rem;
    font-weight: 500;
    color: #333;
    margin-top: 4px;
}

.week-day-date.today {
    background: #1976d2;
    color: #fff;
    width: 32px;
    height: 32px;
    border-radius: 50%;
    display: inline-flex;
    align-items: center;
    justify-content: center;
}

.week-day-events {
    position: relative;
    height: calc(24 * 60px);
}

.week-event {
    position: absolute;
    left: 4px;
    right: 4px;
    padding: 4px 6px;
    border-radius: 4px;
    font-size: 0.75rem;
    color: #fff;
    cursor: pointer;
    overflow: hidden;
}

.week-event:hover {
    opacity: 0.85;
}

/* Day View */
.day-view-grid {
    display: flex;
    min-height: 600px;
}

.day-time-column {
    width: 80px;
    flex-shrink: 0;
    border-right: 1px solid #e0e0e0;
}

.day-time-header {
    height: 80px;
    border-bottom: 1px solid #e0e0e0;
}

.day-time-slots {
    position: relative;
}

.day-time-slot {
    height: 60px;
    border-bottom: 1px solid #f0f0f0;
    padding: 4px 8px;
    font-size: 0.75rem;
    color: #666;
}

.day-events-container {
    flex: 1;
    background: #fff;
    position: relative;
}

.day-header {
    height: 80px;
    border-bottom: 1px solid #e0e0e0;
    padding: 16px;
    text-align: center;
}

.day-date-label {
    font-size: 1.5rem;
    font-weight: 500;
    color: #333;
}

.day-events-timeline {
    position: relative;
    height: calc(24 * 60px);
}

.day-event {
    position: absolute;
    left: 8px;
    right: 8px;
    padding: 8px 12px;
    border-radius: 4px;
    color: #fff;
    cursor: pointer;
    overflow: hidden;
}

.day-event:hover {
    opacity: 0.85;
}

/* Event Detail Modal */
.event-detail-row {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    padding: 12px 0;
    border-bottom: 1px solid #f0f0f0;
}

.event-detail-row:last-child {
    border-bottom: none;
}

.event-detail-row i {
    color: #666;
    width: 20px;
    margin-top: 2px;
}

.event-detail-row span {
    flex: 1;
    color: #333;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    let currentDate = new Date();
    let currentView = 'month';
    let miniCalendarDate = new Date();
    let activeFilters = {
        categories: ['academic', 'sports', 'cultural', 'meeting', 'holiday', 'myanmar']
    };
    
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    
    const categoryColors = {
        academic: '#4285f4', sports: '#34a853', cultural: '#fbbc04', meeting: '#ea4335', holiday: '#9e9e9e', myanmar: '#ff6b35'
    };
    
    // Sample events
    const events = [
        {title: 'Annual Sports Day', date: '2025-10-15', startTime: '09:00', endTime: '15:00', time: '09:00 AM - 03:00 PM', location: 'School Sports Ground', description: 'Annual inter-house sports competition', category: 'sports', grade: 'all', participants: ['students', 'teachers', 'parents']},
        {title: 'Parent-Teacher Meeting', date: '2025-10-20', startTime: '14:00', endTime: '17:00', time: '02:00 PM - 05:00 PM', location: 'Main Hall', description: 'Semester progress discussion', category: 'meeting', grade: 'all', participants: ['parents', 'teachers']},
        {title: 'Science Fair', date: '2025-10-25', startTime: '10:00', endTime: '16:00', time: '10:00 AM - 04:00 PM', location: 'Science Labs', description: 'Student science project exhibition', category: 'academic', grade: 'high', participants: ['students', 'teachers', 'parents']},
        {title: 'Mid-term Exams', date: '2025-10-10', startTime: '08:00', endTime: '12:00', time: '08:00 AM - 12:00 PM', location: 'All Classrooms', description: 'Mid-semester examination', category: 'academic', grade: 'all', participants: ['students', 'teachers']},
        {title: 'Cultural Festival', date: '2025-10-18', startTime: '09:00', endTime: '17:00', time: '09:00 AM - 05:00 PM', location: 'School Auditorium', description: 'Annual cultural program', category: 'cultural', grade: 'all', participants: ['all']},
        {title: 'Independence Day', date: '2025-10-04', startTime: '00:00', endTime: '23:59', time: 'All Day', location: 'School', description: 'National Holiday', category: 'holiday', grade: 'all', participants: ['all']},
        {title: 'Staff Training', date: '2025-10-12', startTime: '09:00', endTime: '16:00', time: '09:00 AM - 04:00 PM', location: 'Conference Room', description: 'Professional development workshop', category: 'meeting', grade: 'all', participants: ['staff', 'teachers']},
        {title: 'Thingyan Water Festival', date: '2025-04-13', startTime: '09:00', endTime: '17:00', time: '09:00 AM - 05:00 PM', location: 'School Grounds', description: 'Myanmar New Year Water Festival', category: 'myanmar', grade: 'all', participants: ['all']},
        {title: 'Buddha Day', date: '2025-05-12', startTime: '08:00', endTime: '12:00', time: '08:00 AM - 12:00 PM', location: 'School Assembly Hall', description: 'Vesak Day - Buddha Birthday Celebration', category: 'myanmar', grade: 'all', participants: ['all']},
        {title: 'Tazaungdaing Festival', date: '2025-11-08', startTime: '18:00', endTime: '22:00', time: '06:00 PM - 10:00 PM', location: 'School Auditorium', description: 'Myanmar Festival of Lights', category: 'myanmar', grade: 'all', participants: ['all']}
    ];
    
    function getFilteredEvents() {
        return events.filter(e => {
            const categoryMatch = activeFilters.categories.includes(e.category);
            return categoryMatch;
        });
    }
    
    // Mini Calendar
    function renderMiniCalendar() {
        const year = miniCalendarDate.getFullYear();
        const month = miniCalendarDate.getMonth();
        document.getElementById('miniMonthLabel').textContent = `${monthNames[month]} ${year}`;
        
        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const daysInPrevMonth = new Date(year, month, 0).getDate();
        const today = new Date();
        
        const grid = document.getElementById('miniCalendar');
        grid.innerHTML = '';
        
        // Weekday labels
        dayNames.forEach(d => {
            const label = document.createElement('div');
            label.className = 'mini-day weekday-label';
            label.textContent = d.charAt(0);
            grid.appendChild(label);
        });
        
        // Previous month
        for (let i = firstDay - 1; i >= 0; i--) {
            const day = document.createElement('div');
            day.className = 'mini-day other-month';
            day.textContent = daysInPrevMonth - i;
            grid.appendChild(day);
        }
        
        // Current month
        for (let d = 1; d <= daysInMonth; d++) {
            const day = document.createElement('div');
            day.className = 'mini-day';
            const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
            const hasEvents = events.some(e => e.date === dateStr);
            if (hasEvents) day.classList.add('has-events');
            if (today.getFullYear() === year && today.getMonth() === month && today.getDate() === d) day.classList.add('today');
            day.textContent = d;
            day.onclick = () => {
                currentDate = new Date(year, month, d);
                renderCurrentView();
            };
            grid.appendChild(day);
        }
    }
    
    // Month View
    function renderMonthView() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        document.getElementById('currentPeriod').textContent = `${monthNames[month]} ${year}`;
        
        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const daysInPrevMonth = new Date(year, month, 0).getDate();
        const grid = document.getElementById('monthGrid');
        grid.innerHTML = '';
        const today = new Date();
        const filtered = getFilteredEvents();
        
        for (let i = firstDay - 1; i >= 0; i--) {
            const cell = document.createElement('div');
            cell.className = 'calendar-day other-month';
            cell.innerHTML = `<div class="calendar-day-number">${daysInPrevMonth - i}</div>`;
            grid.appendChild(cell);
        }
        
        for (let day = 1; day <= daysInMonth; day++) {
            const cell = document.createElement('div');
            cell.className = 'calendar-day';
            const isToday = today.getFullYear() === year && today.getMonth() === month && today.getDate() === day;
            if (isToday) cell.classList.add('today');
            const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            const dayEvents = filtered.filter(e => e.date === dateStr);
            cell.innerHTML = `<div class="calendar-day-number">${day}</div>`;
            if (dayEvents.length > 0) {
                const container = document.createElement('div');
                container.className = 'calendar-events';
                dayEvents.forEach(e => {
                    const evt = document.createElement('div');
                    evt.className = 'calendar-event';
                    evt.style.background = categoryColors[e.category];
                    evt.textContent = e.title;
                    evt.onclick = (ev) => { ev.stopPropagation(); showEventModal(e); };
                    container.appendChild(evt);
                });
                cell.appendChild(container);
            }
            grid.appendChild(cell);
        }
        
        const totalCells = grid.children.length;
        for (let day = 1; day <= 42 - totalCells; day++) {
            const cell = document.createElement('div');
            cell.className = 'calendar-day other-month';
            cell.innerHTML = `<div class="calendar-day-number">${day}</div>`;
            grid.appendChild(cell);
        }
    }
    
    // Week View
    function renderWeekView() {
        const weekStart = new Date(currentDate);
        weekStart.setDate(currentDate.getDate() - currentDate.getDay());
        const weekEnd = new Date(weekStart);
        weekEnd.setDate(weekStart.getDate() + 6);
        
        document.getElementById('currentPeriod').textContent = `${monthNames[weekStart.getMonth()]} ${weekStart.getDate()} - ${monthNames[weekEnd.getMonth()]} ${weekEnd.getDate()}, ${weekStart.getFullYear()}`;
        
        // Time slots
        const timeSlotsContainer = document.getElementById('weekTimeSlots');
        timeSlotsContainer.innerHTML = '';
        for (let h = 0; h < 24; h++) {
            const slot = document.createElement('div');
            slot.className = 'week-time-slot';
            slot.textContent = `${String(h).padStart(2, '0')}:00`;
            timeSlotsContainer.appendChild(slot);
        }
        
        // Week days
        const daysContainer = document.getElementById('weekDaysContainer');
        daysContainer.innerHTML = '';
        const today = new Date();
        const filtered = getFilteredEvents();
        
        for (let i = 0; i < 7; i++) {
            const day = new Date(weekStart);
            day.setDate(weekStart.getDate() + i);
            const col = document.createElement('div');
            col.className = 'week-day-column';
            const isToday = day.toDateString() === today.toDateString();
            const dateStr = `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, '0')}-${String(day.getDate()).padStart(2, '0')}`;
            const dayEvents = filtered.filter(e => e.date === dateStr);
            
            col.innerHTML = `
                <div class="week-day-header">
                    <div class="week-day-name">${dayNames[day.getDay()]}</div>
                    <div class="week-day-date ${isToday ? 'today' : ''}">${day.getDate()}</div>
                </div>
                <div class="week-day-events" id="weekDay${i}"></div>
            `;
            daysContainer.appendChild(col);
            
            const eventsContainer = document.getElementById(`weekDay${i}`);
            dayEvents.forEach(e => {
                const [startH, startM] = e.startTime.split(':').map(Number);
                const [endH, endM] = e.endTime.split(':').map(Number);
                const top = (startH * 60 + startM);
                const height = ((endH * 60 + endM) - (startH * 60 + startM));
                const evt = document.createElement('div');
                evt.className = 'week-event';
                evt.style.top = `${top}px`;
                evt.style.height = `${height}px`;
                evt.style.background = categoryColors[e.category];
                evt.textContent = e.title;
                evt.onclick = () => showEventModal(e);
                eventsContainer.appendChild(evt);
            });
        }
    }
    
    // Day View
    function renderDayView() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        const day = currentDate.getDate();
        document.getElementById('currentPeriod').textContent = `${dayNames[currentDate.getDay()]}, ${monthNames[month]} ${day}, ${year}`;
        
        // Time slots
        const timeSlotsContainer = document.getElementById('dayTimeSlots');
        timeSlotsContainer.innerHTML = '';
        for (let h = 0; h < 24; h++) {
            const slot = document.createElement('div');
            slot.className = 'day-time-slot';
            slot.textContent = `${String(h).padStart(2, '0')}:00`;
            timeSlotsContainer.appendChild(slot);
        }
        
        // Events
        const eventsContainer = document.getElementById('dayEventsContainer');
        eventsContainer.innerHTML = `<div class="day-header"><div class="day-date-label">${monthNames[month]} ${day}</div></div><div class="day-events-timeline" id="dayTimeline"></div>`;
        const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const filtered = getFilteredEvents();
        const dayEvents = filtered.filter(e => e.date === dateStr);
        const timeline = document.getElementById('dayTimeline');
        
        dayEvents.forEach(e => {
            const [startH, startM] = e.startTime.split(':').map(Number);
            const [endH, endM] = e.endTime.split(':').map(Number);
            const top = (startH * 60 + startM);
            const height = ((endH * 60 + endM) - (startH * 60 + startM));
            const evt = document.createElement('div');
            evt.className = 'day-event';
            evt.style.top = `${top}px`;
            evt.style.height = `${height}px`;
            evt.style.background = categoryColors[e.category];
            evt.innerHTML = `<strong>${e.title}</strong><br>${e.time}`;
            evt.onclick = () => showEventModal(e);
            timeline.appendChild(evt);
        });
    }
    
    function renderCurrentView() {
        if (currentView === 'month') renderMonthView();
        else if (currentView === 'week') renderWeekView();
        else if (currentView === 'day') renderDayView();
        renderMiniCalendar();
    }
    
    let currentModalEvent = null;

    function showEventModal(event) {
        document.getElementById('eventModalTitle').textContent = event.title;
        document.getElementById('eventModalTime').textContent = event.time;
        document.getElementById('eventModalLocation').textContent = event.location;
        document.getElementById('eventModalDescription').textContent = event.description;
        currentModalEvent = event;
        document.getElementById('eventModal').style.display = 'flex';
    }
    
    window.closeEventModal = function() {
        document.getElementById('eventModal').style.display = 'none';
    };

    // Navigate to event detail from modal
    window.viewEventDetailFromModal = function() {
        if (!currentModalEvent) return;
        // Build a simple event id based on title if no id exists in data
        const eventId = currentModalEvent.id || (currentModalEvent.title ? `EVT_${encodeURIComponent(currentModalEvent.title).replace(/%20/g,'_')}` : 'EVT');
        window.location.href = `/admin/event-details?id=${eventId}`;
    }
    
    // View toggle
    document.querySelectorAll('.view-toggle-btn').forEach(btn => {
        btn.addEventListener('click', function() {
            document.querySelectorAll('.view-toggle-btn').forEach(b => b.classList.remove('active'));
            this.classList.add('active');
            currentView = this.getAttribute('data-view');
            document.querySelectorAll('.calendar-view-container').forEach(v => v.style.display = 'none');
            document.getElementById(`${currentView}View`).style.display = 'block';
            renderCurrentView();
        });
    });
    
    // Navigation
    document.getElementById('prevPeriod').addEventListener('click', function() {
        if (currentView === 'month') currentDate.setMonth(currentDate.getMonth() - 1);
        else if (currentView === 'week') currentDate.setDate(currentDate.getDate() - 7);
        else if (currentView === 'day') currentDate.setDate(currentDate.getDate() - 1);
        renderCurrentView();
    });
    
    document.getElementById('nextPeriod').addEventListener('click', function() {
        if (currentView === 'month') currentDate.setMonth(currentDate.getMonth() + 1);
        else if (currentView === 'week') currentDate.setDate(currentDate.getDate() + 7);
        else if (currentView === 'day') currentDate.setDate(currentDate.getDate() + 1);
        renderCurrentView();
    });
    
    
    // Mini calendar navigation
    document.getElementById('miniPrev').addEventListener('click', function() {
        miniCalendarDate.setMonth(miniCalendarDate.getMonth() - 1);
        renderMiniCalendar();
    });
    
    document.getElementById('miniNext').addEventListener('click', function() {
        miniCalendarDate.setMonth(miniCalendarDate.getMonth() + 1);
        renderMiniCalendar();
    });
    
    // Category Tag Filters
    document.querySelectorAll('.category-tag').forEach(tag => {
        tag.addEventListener('click', function() {
            const cat = this.getAttribute('data-category');
            if (this.classList.contains('active')) {
                this.classList.remove('active');
                activeFilters.categories = activeFilters.categories.filter(c => c !== cat);
            } else {
                this.classList.add('active');
                activeFilters.categories.push(cat);
            }
            renderCurrentView();
        });
    });
    
    
    // Initial render
    renderCurrentView();
});
</script>

<?php
$content = ob_get_clean();
include __DIR__ . '/../components/staff-layout.php';
?>

